activityScheduleAssigner: standard
carOwnership:
  engine: config/leopoldshafen/parameters/SociodemographicCoefficients.txt
  ownership: config/leopoldshafen/parameters/CarOwnershipModelParameter.txt
  segment: config/leopoldshafen/parameters/LogitBasedCarSegmentModelParameter.txt
#mobilityProviders:
commuterTicket: config/leopoldshafen/parameters/TransitPassParameter.txt
dataSource: !file
  demandDataFolder: output/demand-data-local
  matrixConfigurationFile: data/ipu/leopoldshafen/matrices/matrix-configuration.yaml
  attractivityDataFile: data/ipu/leopoldshafen/zoneproperties/attractivities.csv
  zonePropertiesDataFile: data/ipu/leopoldshafen/zoneproperties/attractivities.csv
  parkingFacilitiesDataFile: data/ipu/leopoldshafen/zoneproperties/parkingFacilities.csv
  bikeSharingPropertiesDataFile: data/ipu/leopoldshafen/zoneproperties/bikesharing-properties.csv
  carSharingPropertiesDataFile: data/ipu/leopoldshafen/zoneproperties/carsharing-properties.csv
  carSharingStationsDataFile: data/ipu/leopoldshafen/zoneproperties/carsharing-stations.csv
  carSharingFreeFloatingDataFile: data/ipu/leopoldshafen/zoneproperties/carsharing-free-floating.csv
  #charging: unlimited
  defaultChargingPower: config/leopoldshafen/parameters/ChargingPower.txt
  zoneRepositoryFolder: output/zone-repository/
demographyData: 
  age_f: data/ipu/leopoldshafen/leopoldshafen-Demography.csv
  age_m: data/ipu/leopoldshafen/leopoldshafen-Demography.csv
  household_size: data/ipu/leopoldshafen/leopoldshafen-Demography.csv
maxIterations: 100
maxGoodnessDelta: 1e-5
#numberOfZones: 2147483647
panelData: data/ipu/leopoldshafen/population.csv
resultFolder: results/population-synthesis
seed: 77859
visumFile: data/ipu/leopoldshafen/leopoldshafen.net
visumToMobitopp:
  carTransportSystemCode: P
experimental:
  communityToZone: data/ipu/leopoldshafen/community-to-zone.csv
  communityCommuters: data/ipu/leopoldshafen/community-to-community-commuters.csv
  poleDistanceRange: 50
