dataSource: !file
  demandDataFolder: output/demand-data-local
  matrixConfigurationFile: data/ipu/leopoldshafen/matrices/matrix-configuration.yaml
  attractivityDataFile: data/ipu/leopoldshafen/zoneproperties/attractivities.csv
  zonePropertiesDataFile: data/ipu/leopoldshafen/zoneproperties/attractivities.csv
  parkingFacilitiesDataFile: data/ipu/leopoldshafen/zoneproperties/parkingFacilities.csv
  carSharingStationsDataFile: data/ipu/leopoldshafen/zoneproperties/carsharingstations.csv
  #charging: unlimited
  defaultChargingPower: config/leopoldshafen/parameters/ChargingPower.txt
  zoneRepositoryFolder: output/zone-repository/
days: 7
destinationChoice:
  repetition: config/leopoldshafen/parameters/TargetParameterRepetition.csv
  cost: config/leopoldshafen/parameters/TargetParameterCost.txt
fractionOfPopulation: 0.10
#numberOfZones: 1174
resultFolder: results/simulation
seed: 1234
visumFile: data/ipu/leopoldshafen/leopoldshafen.net
#experimental:
#  parameter1: 1
#  parameter2: 2