#This is the config to use for urbansim integration. DemographyData is different.
activityScheduleAssigner: standard
carOwnership:
  engine: data_shortterm/parameters/SociodemographicCoefficients.txt
  ownership: data_shortterm/parameters/CarOwnershipModelParameter.txt
  segment: data_shortterm/parameters/LogitBasedCarSegmentModelParameter.txt
#mobilityProviders:
commuterTicket: data_shortterm/parameters/TransitPassParameter.txt
dataSource: !file
  demandDataFolder: output/demand-data
  matrixConfigurationFile: data_shortterm/matrices/matrix-configuration.yaml
  attractivityDataFile: data_shortterm/zone_properties/attractivities.csv
  zonePropertiesDataFile: data_shortterm/zone_properties/zone-properties.csv
  parkingFacilitiesDataFile: data_shortterm/zone_properties/parking-facilities.csv
  bikeSharingPropertiesDataFile: data_shortterm/zone_properties/bikesharing-properties.csv
  carSharingPropertiesDataFile: data_shortterm/zone_properties/carsharing-properties.csv
  carSharingStationsDataFile: data_shortterm/zone_properties/carsharing-stations.csv
  carSharingFreeFloatingDataFile: data_shortterm/zone_properties/carsharing-free-floating.csv
  #charging: unlimited
  defaultChargingPower: data_shortterm/parameters/ChargingPower.txt
  zoneRepositoryFolder: output/zone-repository/
demographyData:
  age_f: data_shortterm/zone_properties/urbansim_demography_ipf.csv
  age_m:  data_shortterm/zone_properties/urbansim_demography_ipf.csv
  dom_code:  data_shortterm/zone_properties/urbansim_demography_ipf.csv
  job: data_shortterm/zone_properties/urbansim_demography_ipf.csv
#numberOfZones: 2147483647
panelData: data_shortterm/clayton_map/clayton-population.csv
resultFolder: results/population-synthesis
seed: 77859
synthesisZoneProperties: data_shortterm/zone_properties/synthesis-zone-properties.csv
visumFile: data_shortterm/clayton_map/Melbourne2023v2.net
pois: data_shortterm/zone_properties/Clayton_12km_Opportunity_Poi.csv
#experimental:
#  parameter1: 1
#  parameter2: 2
