activityScheduleAssigner: standard
carOwnership:
  engine: data_longterm/parameters/SociodemographicCoefficients.txt
  ownership: data_longterm/parameters/CarOwnershipModelParameter.txt
  segment: data_longterm/parameters/LogitBasedCarSegmentModelParameter.txt
#mobilityProviders:
commuterTicket: data_longterm/parameters/TransitPassParameter.txt
dataSource: !file
  demandDataFolder: output/long_term/demand-data
  matrixConfigurationFile: data_longterm/matrices/matrix-configuration.yaml
  attractivityDataFile: data_longterm/zone_properties/attractivities.csv
  zonePropertiesDataFile: data_longterm/zone_properties/zone-properties.csv
  parkingFacilitiesDataFile: data_longterm/zone_properties/parking-facilities.csv
  bikeSharingPropertiesDataFile: data_longterm/zone_properties/bikesharing-properties.csv
  carSharingPropertiesDataFile: data_longterm/zone_properties/carsharing-properties.csv
  carSharingStationsDataFile: data_longterm/zone_properties/carsharing-stations.csv
  carSharingFreeFloatingDataFile: data_longterm/zone_properties/carsharing-free-floating.csv
  #charging: unlimited
  defaultChargingPower: data_longterm/parameters/ChargingPower.txt
  zoneRepositoryFolder: output/long_term/zone-repository/
demographyData:
  age_f: data_longterm/zone_properties/demography-ipf.csv
  age_m: data_longterm/zone_properties/demography-ipf.csv
  dom_code: data_longterm/zone_properties/demography-ipf.csv
  job: data_longterm/zone_properties/demography-ipf.csv
#numberOfZones: 2147483647
panelData: data_longterm/metro_mel_map/clayton-population.csv
resultFolder: results/long_term/population-synthesis
seed: 1234
synthesisZoneProperties: data_longterm/zone_properties/synthesis-zone-properties.csv
visumFile: data_longterm/metro_mel_map/metro_mel_30lga_21sa2.net
pois: data_longterm/zone_properties/metro_mel_30lga_21sa2_alloppo_poi.csv
#experimental:
#  parameter1: 1
#  parameter2: 2
