dataSource: !file
  demandDataFolder: output/emission/demand-data
  matrixConfigurationFile: data_emission/matrices/matrix-configuration.yaml
  attractivityDataFile: data_emission/zone_properties/attractivities.csv
  zonePropertiesDataFile: data_emission/zone_properties/zone-properties.csv
  parkingFacilitiesDataFile: data_emission/zone_properties/parking-facilities.csv

  bikeSharingPropertiesDataFile: data_emission/zone_properties/bikesharing-properties.csv
  carSharingPropertiesDataFile: data_emission/zone_properties/carsharing-properties.csv
  carSharingStationsDataFile: data_emission/zone_properties/carsharing-stations.csv
  carSharingFreeFloatingDataFile: data_emission/zone_properties/carsharing-free-floating.csv
  defaultChargingPower: data_emission/parameters/ChargingPower.txt
  zoneRepositoryFolder: output/emission/zone-repository/
days: 7
modeChoice:
  firstTrip: data_emission/parameters/ModeSelectorParameterFirstTrip.txt
  otherTrip: data_emission/parameters/ModeSelectorParameterOtherTrip.txt
destinationChoice:
  repetition: data_emission/parameters/TargetParameterRepetition.csv
  cost: data_emission/parameters/TargetParameterCost.txt
fractionOfPopulation: 0.005
#numberOfZones: 6
resultFolder: results/emission/simulation
seed: 1234
visumFile: data_emission/study_map/mel_emission_area.net
experimental:
  iterations: 2
  matsimConfig: config/emission/matsim-config.xml
  #facilities: facilities/measure-facilities-12km-destination.xml
  externalTraffic: data_emission/external_demand/external-demand.mtx
  travelTimeMatrixFolderName: travelTime
